#!/usr/local/bin/bash
readonly PROGNAME=$(basename "$0")
readonly ARGS=( "$@" )

shc() {
    local RESET=
    local count=
    local spaces=
    RESET=$(tput sgr0)
    spaces="  "
    count=1
    for i in {1..255}; do
        if [[ $i -gt 99 ]]; then
            spaces=""
        elif [[ $i -gt 9 ]]; then
            spaces=" "
        fi

        printf "%s" "$spaces$(tput setaf $i)$i "

        if [[ $count -eq 20 ]]; then
            printf "\n"
            count=1
        else
            count=$((count+1))
        fi
    done
    printf "%s" "$RESET"
}

shc
